### ISSUE TITLE
[Question] How does fetchBlogSource work?

### ISSUE THREAD

**Issue by terenced** [bobaekang/bobaekangdotcom#1]
Hi!

I found your site because of the video Theo Brown made on your post - absolutely loved it!

I current updated my personal site and was looking the source code of yours for a little inspiration/ideas. I have a few questions regarding fetchBlogSource. 

It seems that it copies the content from another repo in this sites content directory. I was wondering why and when do you run it?
I assume it is run just before the Astro build is run - either in CI or wherever you build/deploy to. Am I correct? How is it working out? 

Cheers,
Terry

**Comment by bobaekang** [comment]
Hey @terenced. Thanks for stopping by! I use Netlify to host my site and it runs `npm run fetch-blog-source && npm run build` for build command. That is, I run the fetch script before prod build so that it can have the latest blog source files. 

That said, `fetchBlogSource.js` is really just a basic thing that doesn't do anything fancy. It gets environment variables `BLOG_SRC_URL` and `GITHUB_TOKEN` and use that to grab source files (blog texts and images), process the content as needed, and write to disk. It's probably not even that well written code but it does what I need and only runs occasionally, so I don't mind.

I originally came up with this step because I was migrating my blog from Gatsby to Astro and didn't want to copy paste blog source files between two repos. Since the migration has been completed, I can move the source files to this repo but I kinda like that the contents live independently of the site for now. 😄

**Comment by terenced** [comment]
Thank you @bobaekang !!
I definitely think there is an advantage to having the content love in a separate repo.
